# Generated by scripts/render-formula.sh — edit the script, not this file.
class Athena < Formula
  desc "Athena Intelligence command-line interface"
  homepage "https://github.com/Athena-Intel/athena-cli"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Athena-Intel/athena-cli/releases/download/v0.3.1/athena-0.3.1-aarch64-apple-darwin.tar.gz"
      sha256 "7453a0723179b2584255dd1a43413bc1bd5f92186c51fd9093971401aad792f9"
    end
    on_intel do
      url "https://github.com/Athena-Intel/athena-cli/releases/download/v0.3.1/athena-0.3.1-x86_64-apple-darwin.tar.gz"
      sha256 "3eb501ead6c0905f3066e5fdcf26afc76070bc7bcb1a0cffc596c9b7b5433eb8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Athena-Intel/athena-cli/releases/download/v0.3.1/athena-0.3.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "77825af06e6b1285d8d49292a10bf73aebf3f213aa4ab0628265ffac894bd291"
    end
    on_intel do
      url "https://github.com/Athena-Intel/athena-cli/releases/download/v0.3.1/athena-0.3.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2c7b9f5404bd1e009d66a2cc266ef9edd6d8de0115152494d611ef6d1dd1dedd"
    end
  end

  def install
    bin.install "athena"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/athena --version")
  end
end
