# Generated by scripts/render-formula.sh — edit the script, not this file.
class Athena < Formula
  desc "Athena Intelligence command-line interface"
  homepage "https://github.com/Athena-Intel/athena-cli"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Athena-Intel/athena-cli/releases/download/v0.7.0/athena-0.7.0-aarch64-apple-darwin.tar.gz"
      sha256 "0e26a861bedb54053093aa6586453c977b9901795f520a0db9295bbe32d2f715"
    end
    on_intel do
      url "https://github.com/Athena-Intel/athena-cli/releases/download/v0.7.0/athena-0.7.0-x86_64-apple-darwin.tar.gz"
      sha256 "cb094b003cee6e4524473d298384681c9725fe0cb3797d43eb4e25495934b8d3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Athena-Intel/athena-cli/releases/download/v0.7.0/athena-0.7.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1545d329c0d2b4588b8bc9d32f0cdac120b5185e70aae9a1543b0b2a98dab3d9"
    end
    on_intel do
      url "https://github.com/Athena-Intel/athena-cli/releases/download/v0.7.0/athena-0.7.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "09dc397be15cce2b817161968b411b4e82b16fc1be6528716de25da2bc672170"
    end
  end

  def install
    bin.install "athena"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/athena --version")
  end
end
