#!/bin/sh
# Render Formula/athena.rb for one athena-cli release.
#
#   sh scripts/render-formula.sh <version> <path-to-SHA256SUMS> > Formula/athena.rb
#
# The SHA256SUMS file is the one attached to the GitHub release; every
# platform's checksum is read from it, never computed here, so the formula
# always pins exactly what the release workflow published.
set -eu
VERSION="$1"
SUMS="$2"
REPO="Athena-Intel/athena-cli"
# Linux x86_64 ships the static musl build: the gnu tarballs are linked against
# the glibc of the GitHub runner that built them (2.39 for 0.3.1) and fail on
# Ubuntu 22.04 / Debian 12 with "GLIBC_2.39 not found". No aarch64 musl build
# is published yet, so Linux arm64 stays on the gnu tarball.

sum_for() {
  target="$1"
  want="athena-${VERSION}-${target}.tar.gz"
  found="$(awk -v f="$want" '$2 == f { print $1 }' "$SUMS")"
  if [ -z "$found" ]; then
    echo "render-formula: no checksum for ${want} in ${SUMS}" >&2
    exit 1
  fi
  printf '%s' "$found"
}

url_for() {
  printf 'https://github.com/%s/releases/download/v%s/athena-%s-%s.tar.gz' "$REPO" "$VERSION" "$VERSION" "$1"
}

cat <<RUBY
# Generated by scripts/render-formula.sh — edit the script, not this file.
class Athena < Formula
  desc "Athena Intelligence command-line interface"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$(url_for aarch64-apple-darwin)"
      sha256 "$(sum_for aarch64-apple-darwin)"
    end
    on_intel do
      url "$(url_for x86_64-apple-darwin)"
      sha256 "$(sum_for x86_64-apple-darwin)"
    end
  end

  on_linux do
    on_arm do
      url "$(url_for aarch64-unknown-linux-gnu)"
      sha256 "$(sum_for aarch64-unknown-linux-gnu)"
    end
    on_intel do
      url "$(url_for x86_64-unknown-linux-musl)"
      sha256 "$(sum_for x86_64-unknown-linux-musl)"
    end
  end

  def install
    bin.install "athena"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/athena --version")
  end
end
RUBY
